In [139]:
import pandas as pd

perguntas = pd.read_csv("data/stackoverflow.csv")
perguntas.sample(10)

                                              Perguntas                 Tags
816   Eu estou tentando passar uma dependência no me...              angular
762   Supondo uma página que tenha vários eventos se...               jquery
226   Tenho um pedido ajax com o seguinte código:  C...                html
4518  Segue abaixo o que eu consegui fazer: Quando c...               jquery
1251    Olá! Eu gostaria de saber como faço para que...          jquery html
4131  Tenho um código em CODE  que faz uma busca em ...              jquery
3460  Possuo um select que ao selecionar a opção Bra...               jquery
2457  Está dando esse erro quando adiciono um novo i...              angular
4711  Tenho este trecho de código, que mostra uma im...              angular
5333  Está sendo enviado do servidor para esta view ...  jquery html node.js

In [140]:
print(len(perguntas))

5408

In [141]:
perguntas.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [142]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)
        
print(lista_de_tags)

['node.js', 'jquery', 'html', 'angular']

In [143]:
node_js = list()
for linha_tag in perguntas.Tags:
    if "node.js" in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
perguntas["node.js"] = node_js
perguntas

,Perguntas,Tags,node.js
0,Possuo um projeto Node.js porém preciso criar ...,node.js,1
1,"Gostaria de fazer testes unitários no Node.js,...",node.js,1
2,Como inverter a ordem com que o jQuery itera u...,jquery,0
3,Eu tenho uma página onde pretendo utilizar um ...,html,0
4,Como exibir os dados retornados do FireStore e...,html angular,0
...,...,...,...
5403,Queria saber como pegar o total de cores de um...,jquery html,0
5404,"Boa noite, estou usando phonegap para fazer um...",html,0
5405,"Estou construindo um mini fórum, e nele, os us...",jquery html,0
5406,"Boa tarde, Estou para desenvolver um site na ...",html,0
5407,"Estou fazendo um hotsite, ele é one page, e é ...",jquery html,0

In [144]:
def nova_coluna(lista_tags, dataframe, nome_tags):
    for tag in lista_tags:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)
            else:
                coluna.append(0)
        dataframe[tag] = coluna
nova_coluna(lista_de_tags, perguntas, "Tags")
perguntas.sample(10)

,Perguntas,Tags,node.js,jquery,html,angular
281,"Boa noite,tenho um projeto em html, já está na...",html,0,0,1,0
4586,Queria saber como faço para que assim que clic...,jquery,0,1,0,0
1193,Estou tentando modificar a cor de fundo do meu...,html,0,0,1,0
623,Eu tenho uma pagina onde exibo alguns áudios q...,jquery,0,1,0,0
381,"Estou desenvolvendo uma tabela de planos, onde...",html,0,0,1,0
2817,De que forma posso setar como obrigatórios cam...,html angular,0,0,1,1
4459,Estou utilizando um webService (viaCep) para p...,jquery html angular,0,1,1,1
783,Tenho uma aplicação AngularJs+Node(Express) to...,angular node.js,1,0,0,1
4392,"Estou fazendo uma ""UI"" com Canvas, onde apenas...",html,0,0,1,0
1352,"Estou verificando um form com o CODE , porém m...",html,0,0,1,0

In [145]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas['Perguntas'],
    perguntas['Tags']
)

In [146]:
lista_1 = [1,2]
lista_2 = [5,4]
lista_zip = zip(lista_1, lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]

In [147]:
lista_zip_tags = list(zip(perguntas[lista_de_tags[0]],
                     perguntas[lista_de_tags[1]],
                     perguntas[lista_de_tags[2]],
                     perguntas[lista_de_tags[3]]))

perguntas["todas_tags"] = lista_zip_tags
perguntas.sample(10)

,Perguntas,Tags,node.js,jquery,html,angular,todas_tags
2955,"Olá, estou desenvolvendo uma função para resol...",jquery,0,1,0,0,"(0, 1, 0, 0)"
308,"Bem, preciso obter um parâmetro da minha url a...",angular,0,0,0,1,"(0, 0, 0, 1)"
1270,Tenho um código aonde ele cria um tabela caso ...,jquery,0,1,0,0,"(0, 1, 0, 0)"
4876,"Desenvolvendo um sistema simples, me deparei c...",angular,0,0,0,1,"(0, 0, 0, 1)"
2041,seguinte: Comecei literalmente hoje a trabalh...,node.js,1,0,0,0,"(1, 0, 0, 0)"
260,É possível criar uma lockscreen em JS+HTML+CSS...,html,0,0,1,0,"(0, 0, 1, 0)"
3749,"Tenho este motor de busca simples, funciona em...",html,0,0,1,0,"(0, 0, 1, 0)"
3679,Estou tentando acessar um webservice usando No...,node.js,1,0,0,0,"(1, 0, 0, 0)"
4618,Tenho a estrutura abaixo. Preciso acessar cada...,jquery,0,1,0,0,"(0, 1, 0, 0)"
4131,Tenho um código em CODE que faz uma busca em ...,jquery,0,1,0,0,"(0, 1, 0, 0)"

In [148]:
lista_de_tags

['node.js', 'jquery', 'html', 'angular']

In [149]:
from sklearn.model_selection import train_test_split

perguntas_treino, perguntas_test, tags_treino, tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)

In [150]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [151]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features=5000, max_df=0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [152]:
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_test_tfidf = vetorizar.transform(perguntas_test)
print(perguntas_treino_tfidf.shape)
print(perguntas_test_tfidf.shape)

(4326, 5000)
(1082, 5000)

In [153]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_test_array = np.asarray(list(tags_teste))

In [154]:
tags_treino_array

array([[0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       ...,
       [0, 1, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 0]], shape=(4326, 4))

In [155]:
type(tags_treino)

pandas.core.series.Series

In [156]:
type(tags_treino)

pandas.core.series.Series

In [157]:
import numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))
print(tags_treino_array)
print(type(tags_treino_array))

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>

In [158]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)
classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print("Resultado {0: .2f}%".format(resultado_onevsrest*100))

Resultado  41.87%

In [159]:
perguntas.todas_tags.unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [160]:
len(perguntas.todas_tags.unique())

13

In [161]:
1/13

0.07692307692307693

In [162]:
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)
print("Hamming Loss {0: .2f}".format(hamming_loss_onevsrest))

Hamming Loss  0.19

In [163]:
from skmultilearn.problem_transform import ClassifierChain

classificador_cadeia = ClassifierChain(regressao_logistica)
classificador_cadeia.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_cadeia = classificador_cadeia.score(perguntas_test_tfidf, tags_teste_array)
previsao_cadeia = classificador_cadeia.predict(perguntas_test_tfidf)
hamming_loss_cadeia = hamming_loss(tags_teste_array, previsao_cadeia)
print("Hamming Loss {0: .2f}".format(hamming_loss_cadeia))
print("Resultado {0: .2f}%".format(resultado_cadeia*100))

Hamming Loss  0.21
Resultado  49.54%

In [164]:
from skmultilearn.problem_transform import BinaryRelevance

classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_br = classificador_br.score(perguntas_test_tfidf, tags_teste_array)
previsao_br = classificador_br.predict(perguntas_test_tfidf)
hamming_loss_br = hamming_loss(tags_teste_array, previsao_br)
print("Hamming Loss {0: .2f}".format(hamming_loss_br))
print("Resultado {0: .2f}%".format(resultado_br*100))

Hamming Loss  0.19
Resultado  41.87%

In [165]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss

classificador_mlknn = OneVsRestClassifier(KNeighborsClassifier(n_neighbors=5))
classificador_mlknn.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_mlknn = classificador_mlknn.score(perguntas_test_tfidf, tags_teste_array)

previsao_mlknn = classificador_mlknn.predict(perguntas_test_tfidf)

hamming_loss_mlknn = hamming_loss(tags_teste_array, previsao_mlknn)

print("Hamming Loss {0:.2f}".format(hamming_loss_mlknn))
print("Resultado {0:.2f}%".format(resultado_mlknn * 100))

Hamming Loss 0.25
Resultado 32.16%

In [166]:
print("Hamming Loss cadeia {0: .2f}".format(hamming_loss_cadeia))
print("Resultado cadeia {0: .2f}%".format(resultado_cadeia*100))

Hamming Loss cadeia  0.21
Resultado cadeia  49.54%

In [167]:
previsao_br

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 966 stored elements and shape (1082, 4)>

In [168]:
resultados_classificacao.iloc[1]

perguntas    Estou fazendo um site que eu sou obrigado a us...
tags real                                         (0, 0, 1, 0)
BR                                                [0, 0, 1, 0]
cadeia                                    [0.0, 0.0, 1.0, 0.0]
Name: 1, dtype: object

In [169]:
resultados_classificacao.perguntas[1]

'Estou fazendo um site que eu sou obrigado a usar HTML, CSS e JavaScript no máximo. Só que muitas coisas que eu preciso do PhP eu não posso usar. Sendo assim eu estive pesquisando por sinonimo de CODE  e encontrei o seguinte, que ajudou em partes:  CODE   Tá, mas qual é o problema? Ele cria uma barra de rolagem do lado. Eu sei como remover com CSS, mas o texto que foi inserido rola só dentro da área da CODE  e eu queria que fizesse como se o texto inserido fizesse parte da página, como funciona no CODE  do PhP. A questão é, como fazer a mecânica do JavaScript nesse caso ficar igual ao do PhP?  Print para exemplificar: https://imgur.com/a/V9AGLgB '